name: Update live branch
on:
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC
  push:
    branches:
      - master
    paths:
      - 'registry/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Checkout index
        uses: actions/checkout@v2
        with:
          ref: index
          path: index
          token: ${{ secrets.BSDATABOT_TOKEN }}
      - name: Compile index
        uses: ./.github/actions/compile-index
        id: compile
        with:
          index-path: ./index
          registry-path: ./master/registry
      - name: Commit and push any changes
        shell: pwsh
        working-directory: ./index
        env:
          commit_message: ${{ steps.compile.commit-message }}
        run: |
          if (git status --porcelain) {
            git add *.yml
            git commit --message $env:commit_message
            git push
          } else { Write-Host 'No changes in the index' -ForegroundColor Green }
